version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - ./certs:/etc/nginx/certs
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - ./certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy:rw

  cqrabogados-nginx:
    container_name: cqrabogados-nginx
    build: ./nginx
    restart: always
    expose:
      - '80'
    links:
      - 'cqrabogados-node:server'
    environment:
      VIRTUAL_HOST: cqrabogados.com,www.cqrabogados.com
      LETSENCRYPT_HOST: cqrabogados.com,www.cqrabogados.com
      LETSENCRYPT_EMAIL: nacho.vallejos17@outlook.com

  cqrabogados-node:
    container_name: cqrabogados-node
    build: ${CQRABOGADOS_REPO}
    restart: always

  incorporar-nginx:
    container_name: incorporar-nginx
    build: ./nginx
    restart: always
    expose:
      - '80'
    links:
      - 'incorporar-node:server'
    environment:
      VIRTUAL_HOST: in-corporar.com,www.in-corporar.com
      LETSENCRYPT_HOST: in-corporar.com,www.in-corporar.com
      LETSENCRYPT_EMAIL: nacho.vallejos17@outlook.com

  incorporar-node:
    container_name: incorporar-node
    build: ${INCORPORAR_REPO}
    restart: always
